import { evaluatePlan } from './evaluator';
import { runPolicyOnScenario } from './scenarioRunner';
import type {
  EvaluationScore,
  GroundStation,
  ImprovementCycle,
  OrbitalNode,
  PolicyMutation,
  PolicyVersion,
  Scenario,
  ScenarioEvaluationResult,
} from './types';

export function runImprovementCycle(
  primaryScenario: Scenario,
  baselinePolicy: PolicyVersion,
  scenarios: Scenario[],
  nodes: OrbitalNode[],
  stations: GroundStation[],
): ImprovementCycle {
  const baselinePlan = runPolicyOnScenario(primaryScenario, baselinePolicy, nodes, stations);
  const baselineScore = evaluatePlan(primaryScenario, baselinePolicy, baselinePlan, nodes, stations);
  const mutation = createPolicyMutation(primaryScenario, baselinePolicy, baselineScore);
  const scenarioResults = scenarios.map((scenario) =>
    evaluateScenarioPair(scenario, baselinePolicy, mutation.candidatePolicy, nodes, stations),
  );
  const primaryResult = scenarioResults.find((result) => result.scenarioId === primaryScenario.id) ?? scenarioResults[0];
  const averageDelta = Math.round(
    scenarioResults.reduce((sum, result) => sum + result.decision.delta, 0) / Math.max(1, scenarioResults.length),
  );
  const criticalRegression = scenarioResults.some((result) => result.decision.delta < -4);
  const guardrailRegression = scenarioResults.some(
    (result) => result.candidateScore.dimensions.guardrail < result.baselineScore.dimensions.guardrail,
  );
  const promoted = primaryResult.decision.promoted && !criticalRegression && !guardrailRegression;
  const reasons = [
    ...primaryResult.decision.reasons,
    `Average golden-scenario delta: ${averageDelta}.`,
  ];

  if (criticalRegression) {
    reasons.push('Promotion held because at least one golden scenario regressed by more than four points.');
  }

  if (guardrailRegression) {
    reasons.push('Promotion held because a guardrail score regressed.');
  }

  if (promoted) {
    reasons.push('Golden scenario sweep passed without critical regression.');
  }

  return {
    baselinePolicy,
    mutation,
    scenarioResults,
    primaryScenarioId: primaryScenario.id,
    averageDelta,
    promoted,
    reasons,
  };
}

export function createPolicyMutation(
  scenario: Scenario,
  policy: PolicyVersion,
  score: EvaluationScore,
): PolicyMutation {
  const failureDimensions = score.failures.map((failure) => failure.split(':')[0]);
  const candidatePolicy: PolicyVersion = {
    ...policy,
    id: `${policy.id}-${scenario.id}-thermal-contact-candidate`,
    name: 'v1 generated thermal-contact candidate',
    summary: 'Generated mutation that raises thermal, contact, and confidence weighting while reducing compute urgency.',
    weights: {
      ...policy.weights,
      deadline: roundWeight(Math.max(0.9, policy.weights.deadline - 0.35)),
      compute: roundWeight(Math.max(0.85, policy.weights.compute - 0.45)),
      thermal: roundWeight(policy.weights.thermal + (failureDimensions.includes('thermal') ? 1.2 : 0.45)),
      contact: roundWeight(policy.weights.contact + (failureDimensions.includes('contact') ? 1.0 : 0.35)),
      radiation: roundWeight(policy.weights.radiation + (failureDimensions.includes('risk') ? 0.45 : 0.2)),
      confidence: roundWeight(policy.weights.confidence + 0.35),
      dataReduction: roundWeight(policy.weights.dataReduction + 0.1),
    },
    guardrails: Array.from(new Set([...policy.guardrails, 'show confidence limits'])),
    promotedAt: 'Candidate generated by OrbitForge improvement loop',
  };

  return {
    id: `mutation-${scenario.id}-thermal-contact`,
    source: 'deterministic',
    summary: `Responds to ${scenario.name} failures by cooling deadline/compute bias and raising thermal/contact awareness.`,
    targetFailures: score.failures,
    diff: describeDiff(policy, candidatePolicy),
    candidatePolicy,
    expectedEffect: 'Improve thermal, contact, and risk handling without weakening seeded-data guardrails.',
  };
}

function evaluateScenarioPair(
  scenario: Scenario,
  baselinePolicy: PolicyVersion,
  candidatePolicy: PolicyVersion,
  nodes: OrbitalNode[],
  stations: GroundStation[],
): ScenarioEvaluationResult {
  const baselinePlan = runPolicyOnScenario(scenario, baselinePolicy, nodes, stations);
  const candidatePlan = runPolicyOnScenario(scenario, candidatePolicy, nodes, stations);
  const baselineScore = evaluatePlan(scenario, baselinePolicy, baselinePlan, nodes, stations);
  const candidateScore = evaluatePlan(scenario, candidatePolicy, candidatePlan, nodes, stations);
  const decision = {
    baseline: baselineScore,
    candidate: candidateScore,
    delta: candidateScore.total - baselineScore.total,
    promoted:
      candidateScore.total > baselineScore.total &&
      candidateScore.guardrailPassed &&
      candidateScore.dimensions.guardrail >= baselineScore.dimensions.guardrail,
    reasons: [
      candidateScore.total > baselineScore.total
        ? `Candidate improves ${scenario.name} by ${candidateScore.total - baselineScore.total} points.`
        : `Candidate does not improve ${scenario.name}.`,
    ],
  };

  return {
    scenarioId: scenario.id,
    baselinePlan,
    candidatePlan,
    baselineScore,
    candidateScore,
    decision,
  };
}

function describeDiff(before: PolicyVersion, after: PolicyVersion): string[] {
  return Object.entries(after.weights).map(([key, value]) => {
    const oldValue = before.weights[key as keyof PolicyVersion['weights']];
    const sign = value >= oldValue ? '+' : '';

    return `${key}: ${oldValue} -> ${value} (${sign}${roundWeight(value - oldValue)})`;
  });
}

function roundWeight(value: number): number {
  return Math.round(value * 100) / 100;
}
